---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hooks-service
  namespace: k8sdeploy
  labels:
    name: hooks-service
    app: hooks-service
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: hooks-service
  template:
    metadata:
      labels:
        app: hooks-service
        name: hooks-service
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: hooks-service
          image: containers.chewedfeed.com/k8sdeploy/hooks-service:latest
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: DEVELOPMENT
              value: "false"
            - name: SERVICE_NAME
              value: hooks-service

---
apiVersion: v1
kind: Service
metadata:
  name: hooks-service
  namespace: k8sdeploy
  labels:
    app: hooks-service
    name: hooks-service
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      name: http
  selector:
    app: hooks-service

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: k8sdeploy
  name: hooks-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    cert-manager.io/cluster-issuer: acme-prod
  labels:
    app: hooks-service
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - hooks.k8sdeploy.dev
      secretName: hooks-service-k8sdeploy-tls
  rules:
    - host: hooks.k8sdeploy.dev
      http:
        paths:
          - path: /v1/github(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: hooks-service
                port:
                  number: 3000
