---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
  namespace: k8sdeploy
  labels:
    name: orchestrator
    app: orchestrator
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
        name: orchestrator
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: orchestrator
          image: containers.chewedfeed.com/k8sdeploy/orchestrator:latest
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
          ports:
            - containerPort: 3000
              name: http
            - containerPort: 8001
              name: grpc
          env:
            - name: DEVELOPMENT
              value: "false"
            - name: SERVICE_NAME
              value: orchestrator
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: k8sdeploy-vault-token
                  key: token

---
apiVersion: v1
kind: Service
metadata:
  name: orchestrator
  namespace: k8sdeploy
  labels:
    app: orchestrator
    name: orchestrator
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      name: http
    - port: 8001
      protocol: TCP
      targetPort: 8001
      name: grpc
  selector:
    app: orchestrator

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: k8sdeploy
  name: orchestrator-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    cert-manager.io/cluster-issuer: acme-prod
  labels:
    app: orchestrator
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.k8sdeploy.dev
      secretName: orchestrator-k8sdeploy-tls
  rules:
    - host: api.k8sdeploy.dev
      http:
        paths:
          - path: /v1(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: orchestrator-service
                port:
                  number: 3000
